spring:
  application:
    name: chongdae
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 20MB
      max-request-size: 20MB

  springdoc:
    swagger-ui:
      path: swagger-ui.html
      url: /static/swagger-ui/openapi3.yaml

security:
  jwt:
    token:
      access-secret-key: testSecretkey
      refresh-secret-key: testSecretkeytestSecretkeytestSecretkeytestSecretkey
      access-token-expired: 30m
      refresh-token-expired: 14d

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID

amazon:
  s3:
    bucket: techcourse-project-2024
  cloudfront:
    redirectUrl: d3a5rfnjdz82qu.cloudfront.net

