spring:
  application:
    name: chongdae
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 20MB
      max-request-size: 20MB

springdoc:
  swagger-ui:
    path: swagger-ui.html
    url: /static/swagger-ui/openapi3.yaml

amazon:
  s3:
    bucket: techcourse-project-2024
  cloudfront:
    redirectUrl: d3a5rfnjdz82qu.cloudfront.net

security:
  jwt:
    token:
      access-secret-key: ${JWT_ACCESS_SECRET_KEY}
      refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
      access-token-expired: 30m
      refresh-token-expired: 14d

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID

logging:
  level:
    com.zzang.chongdae: INFO
  file:
    name: /logs/backend.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: /logs/backend.%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      max-history: 14
