name: Backend CI/CD Workflow

on:
  pull_request:
    branches: [ "develop-BE" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Application yml for dev
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES_DEV }}" > src/main/resources/application.properties
        working-directory: ./backend

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew clean
          ./gradlew copyOasToSwagger
          ./gradlew build
        working-directory: ./backend

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build and push for dev
        run: |
          docker build -t ${{ secrets.DOCKERHUB_IMAGE_NAME }}:dev .
          docker tag ${{ secrets.DOCKERHUB_IMAGE_NAME }}:dev ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:dev-${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:dev-${GITHUB_SHA::7}

  deploy:
    needs: docker-build-and-push
    runs-on: [ self-hosted, dev ]
